version: '3.1'

services:
  s_jenkins:
    container_name: c_jenkins
    # image: jenkins/jenkins
    image: necipfzlakay/jenkinswithdocker
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/Home/Jenkins/opt:/var/jenkins_home
    build:
      context: .
      dockerfile: Dockerfile
  #//!########################################################
  s_portainer:
    container_name: c_portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  #//!########################################################
  # s_gitlab:
  #   container_name: c_gitlab
  #   image: 'gitlab/gitlab-ee:latest'
  #   restart: always
  #   hostname: 'godzilla.genius99.co'
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'https://godzilla.genius99.co'
  #       # Add any other gitlab.rb configuration here, each on its own line
  #   ports:
  #     # - '80:80'
  #     # - '443:443'
  #     # - '22:22'
  #     - '8092:8929'
  #     - '2224:22'
  #   volumes:
  #     - '/Home/Gitlab/config:/etc/gitlab'
  #     - '/Home/Gitlab/logs:/var/log/gitlab'
  #     - '/Home/Gitlab/data:/var/opt/gitlab'
  #   shm_size: '256m'
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost/80" ]
  #     interval: 1m
  #     timeout: 30s
  #     retries: 3
  #     start_period: 10s

volumes:
  data:

    #//!########################################################
    # s_nginx:
    #   container_name: c_nginx
    #   image: nginx
    #   volumes:
    #     - ./templates:/etc/nginx/templates
    #   ports:
    #     - "8080:80"
    #   environment:
    #     - NGINX_HOST=foobar.com
    #     - NGINX_PORT=80
    #   healthcheck:
    #     test: [ "CMD", "curl", "-f", "http://localhost/80" ]
    #     interval: 30s
    #     timeout: 30s
    #     retries: 3
    #     start_period: 10s
    #//!########################################################
